// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoBuEvR77wDkwEQSIDtOP0MkcFs0xJe0',
    appId: '1:566373144403:android:b8fc7f6b55f7aca21fb3a6',
    messagingSenderId: '566373144403',
    projectId: 'project-kazu-fd451',
    databaseURL: 'https://project-kazu-fd451-default-rtdb.firebaseio.com',
    storageBucket: 'project-kazu-fd451.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnWFLXrzQFTR3HjI2YzBRbh_i4CO2UjA',
    appId: '1:566373144403:ios:88713b0a7f1f54dc1fb3a6',
    messagingSenderId: '566373144403',
    projectId: 'project-kazu-fd451',
    databaseURL: 'https://project-kazu-fd451-default-rtdb.firebaseio.com',
    storageBucket: 'project-kazu-fd451.firebasestorage.app',
    iosBundleId: 'com.example.kazu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhnWFLXrzQFTR3HjI2YzBRbh_i4CO2UjA',
    appId: '1:566373144403:ios:88713b0a7f1f54dc1fb3a6',
    messagingSenderId: '566373144403',
    projectId: 'project-kazu-fd451',
    databaseURL: 'https://project-kazu-fd451-default-rtdb.firebaseio.com',
    storageBucket: 'project-kazu-fd451.firebasestorage.app',
    iosBundleId: 'com.example.kazu',
  );

}